language: node_js
node_js: stable
branches:
  only:
  - master
before_install:
- npm install -g hexo
- npm install -g hexo-cli
install:
- npm install
script:
- yuque-hexo sync && hexo deploy
after_success:
  - cd ./public
  - git init
  - git config --global user.name 'guohuaikun'
  - git config --global user.email 'guohuaikun@souche.com'
  - git add .
  - git commit -m "generate static resources, triggerd by travis ci"
  - git push --force "https://kun95:${REPO_TOKEN}@${GH_REF}" master:master
env:
  global:
    - GH_REF: github.com/kun95/kun95.github.com.git